version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    container_name: frontend
    stdin_open: true
    volumes:
      - './frontend:/app/frontend'
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - '5000:5000'
  #   container_name: backend